### PR TITLE
Flesh out instructions for linking outside libzmq

### PR DESCRIPTION
**Pull request by non-Jedi**
Per discussion in #2, this should help others like me who aren't as familiar with C build processes.

### CODE REVIEW

**Comment by nnicandro** [comment]
Actually, I am trying to get to grips with the build process myself, autoconfigure and friends are pretty complex.

I don't think checking for `ZMQ_BUILD_DRAFT_API` in `ZMQ_CFLAGS` is the way to go since `ZMQ_CFLAGS` is not the only way to set compilation flags. There is also `CFLAGS`.

Before #2 I had automatically checked for DRAFT availability using [AC_CHECK_LIB](https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/Libraries.html), but I switched over to using [PKG_CHECK_MODULES](https://autotools.io/pkgconfig/pkg_check_modules.html) because it was simpler when building libzmq locally. The issue is that the `AC_CHECK_LIB` function makes assumptions about how certain variables in the configure process are used whereas `pkg-config` and therefore `PKG_CHECK_MODULES` doesn't make those same assumptions so there is somewhat of a conflict with using both together which is why I changed over to checking that `ZMQ_BUILD_DRAFT_API` was in `ZMQ_CFLAGS`.

I am working on a fix to bring back the automatic check to see if `libzmq` was built with draft support that it won't be necessary for the user to specify the `ZMQ_BUILD_DRAFT_API` option, so I think I will hold off on this.

**Comment by nnicandro** [comment]
Could you check out #5 and let me know if it works better for your system. You should not have to specify the `ZMQ_BUILD_DRAFT_API` macro.

Then you can update this patch without mention of the macro and I can merge it.

**Comment by non-Jedi** [comment]
#5 works for me without including `ZMQ_BUILD_DRAFT_API`. Thanks. :)

**Comment by vv111y** [comment]
Hi, I'm trying to get this working on a mac and the build fails,

```
ld: warning: ignoring file ./src/.libs/libzmq.a, file was built for archive which is not the architecture being linked (x86_64): ./src/.libs/libzmq.a
Undefined symbols for architecture x86_64:
  "zmq::radix_tree::add(unsigned char const*, unsigned long)", referenced from:
      _main in benchmark_radix_tree-benchmark_radix_tree.o
  "zmq::radix_tree::check(unsigned char const*, unsigned long)", referenced from:
      void benchmark_lookup<zmq::radix_tree>(zmq::radix_tree&, std::__1::vector<unsigned char*, std::__1::allocator<unsigned char*> >&, std::__1::vector<unsigned char*, std::__1::allocator<unsigned char*> >&) in benchmark_radix_tree-benchmark_radix_tree.o
  "zmq::radix_tree::radix_tree()", referenced from:
      _main in benchmark_radix_tree-benchmark_radix_tree.o
  "zmq::radix_tree::~radix_tree()", referenced from:
      _main in benchmark_radix_tree-benchmark_radix_tree.o
  "zmq::trie_t::add(unsigned char*, unsigned long)", referenced from:
      _main in benchmark_radix_tree-benchmark_radix_tree.o
  "zmq::trie_t::check(unsigned char*, unsigned long)", referenced from:
      void benchmark_lookup<zmq::trie_t>(zmq::trie_t&, std::__1::vector<unsigned char*, std::__1::allocator<unsigned char*> >&, std::__1::vector<unsigned char*, std::__1::allocator<unsigned char*> >&) in benchmark_radix_tree-benchmark_radix_tree.o
  "zmq::trie_t::trie_t()", referenced from:
      _main in benchmark_radix_tree-benchmark_radix_tree.o
  "zmq::trie_t::~trie_t()", referenced from:
      _main in benchmark_radix_tree-benchmark_radix_tree.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [perf/benchmark_radix_tree] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [/Users/Will/.emacs.d/private/emacs-zmq/libzmq/build/v4.3.1/lib/pkgconfig/libzmq.pc] Error 2
```
I don't have any experience with C builds either, so I don't know what to do. 

Also, ```make test``` results in  ```Modules not supported```

**Comment by nnicandro** [comment]
@vv111y Could you open a new issue with your problem (https://github.com/dzop/emacs-zmq/issues/new) to discuss this further. 

It looks like your Emacs is not built with module support which is why you are getting the `Modules not supported` error. You need to have an Emacs built with module support. If you use [homebrew](https://brew.sh/) then you can run `brew install emacs --with-modules` and that should get you an Emacs with module support.

**Comment by nnicandro** [comment]
Closing since we have moved to only downloading and statically linking libzmq into the emacs-zmq module. See 1bc8268021e718e1e25b16b318d1e0c10fc053b7.

**Comment by non-Jedi** [comment]
Wait. So there's now no way of linking against libzmq if I have it already installed on my system with the appropriate options? That's rather... annoying.

EDIT: In that case, I'm going to be stuck on v0.10.8.

**Comment by nnicandro** [comment]
Its easier to support both Windows and Unix based environments by statically linking. Windows dynamic library linking does not allow one to embed the path of a dependent library directly in another library. It is easy to describe the `libzmq` dependency of `emacs-zmq` in Unix based environments since the library linker has the concept of a run-time path that can be embedded in the `emacs-zmq.so` file to point to the location of the `libzmq.so` dependency.

Windows does not have the concept of a run-time path for the linker to search, only a set of pre-defined locations it uses to search for libraries which are inconvenient for our purposes.

It was simpler to only support static linking if I wanted to support both Windows and Unix based systems without having to specify caveats when installing on Windows. And I figured most people who are using this package are coming from `emacs-jupyter` and would not have the need to link against their own `libzmq`. That being said, the purpose of this package is not only to support `emacs-jupyter`. It is meant as a general Emacs interface to the `libzmq` library so it should also allow one to link in their own `libzmq`.

**Comment by non-Jedi** [comment]
Thanks. I understand wanting to reduce build system complexity. I should probably file an issue for the JSON-related error I experienced when testing the pre-compiled way, although even if it worked, I probably couldn't use the pre-built binaries.

**Pull request closed without merging**
